---
- hosts: all
  gather_facts: no
  remote_user: ansible
  tasks:
    - name: Test connection
      ping:
      remote_user: ansible
#helo
#what are you doing
      #jfvjnvjnjnfn
      #fj n nd 
      #f dm k

